version: '3'
services:
  social-media-api:
    container_name : backend-api
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://root:example@mongo:27017/?authSource=admin
      - JWT_SECRET=helloworld
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redisexample
      - REDIS_URL=redis://:redisexample@cache:6379
    command: npm run start
    volumes:
      - .:/app
  mongo:
    container_name : mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  cache:
    container_name : redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redisexample
    volumes: 
      - cache:/data


volumes:
  mongo-data:
  cache: